require("dotenv").config();
const express = require("express");
const mongoose = require("mongoose");
const multer = require("multer");
const path = require("path");
const cors = require("cors");
const UserModel = require("./model/User");
const CommentModel = require("./model/Comment");
const CategoryModel = require("./model/Category");
const PostModel = require("./model/Post");
const ContactModel = require("./model/Contact");
const ReportModel = require("./model/Report");
const NotificationModel = require("./model/Notification");
const userRoutes = require("./routes/users");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const nodemailer = require("nodemailer");
const crypto = require("crypto");

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static("public"));

mongoose.connect(process.env.MONGODB_CONNECT_URI);

// mongoose.connect("mongodb://127.0.0.1:27017/node_crud");

//upload image
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "public/Images");
  },
  filename: (req, file, cb) => {
    cb(
      null,
      file.fieldname + "_" + Date.now() + path.extname(file.originalname)
    );
  },
});
const upload = multer({
  storage: storage,
});

// Send mail

// Thiết lập thông tin email
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "huynguyen20521@gmail.com", //generated by Mailtrap
    pass: "zmaxykcjylpfrrss", //generated by Mailtrap
  },
});

//API connect Front-end
const tempStorage = {};

app.get("/send-otp/:email", (req, res) => {
  const email = req.params.email;
  const otp = Math.floor(100000 + Math.random() * 900000);

  tempStorage[email] = otp;

  const mailOptions = {
    from: "huynguyen20521@gmail.com",
    to: `${email}`,
    subject: "Mã OTP cho việc đặt lại mật khẩu",
    text: `Mã OTP của bạn là: ${otp}`,
  };
  // Gửi email
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log("Lỗi khi gửi email:", error);
      res.status(500).send("Lỗi khi gửi email");
    } else {
      console.log("Email đã được gửi:", info.response);
      res.status(200).send("Mã OTP đã được gửi qua email");
    }
  });
});

// Thay doi

// app.get("/verify-otp", async (req, res) => {
//   const { email, otp } = req.query;

//   if (tempStorage[email] && tempStorage[email] == otp) {
//     delete tempStorage[email];
//     const user = await UserModel.findOneAndUpdate(
//       { email: email },
//       {
//         password: "",
//       }
//     );
//     if (user) {
//       res.status(200).send("Thông tin người dùng đã được cập nhật");
//     } else {
//       res.status(404).send("Không tìm thấy người dùng");
//     }
//     console.log("Mã OTP hợp lệ");
//   } else {
//     console.log("Mã OTP không hợp lệ");
//   }
// });

app.get("/verify-otp", async (req, res) => {
  try {
    const { email, otp } = req.query;

    if (tempStorage[email] && tempStorage[email] == otp) {
      delete tempStorage[email];
      const user = await UserModel.findOneAndUpdate(
        { email: email },
        {
          password: "",
        }
      );
      if (user) {
        res.status(200).send("Thông tin người dùng đã được cập nhật");
      } else {
        res.status(404).send("Không tìm thấy người dùng");
      }
      console.log("Mã OTP hợp lệ");
    } else {
      console.log("Mã OTP không hợp lệ");
      res.status(400).send("Mã OTP không hợp lệ");
    }
  } catch (error) {
    console.error(error);
    res.status(500).send("Lỗi server");
  }
});

// thay doi

// app.put("/changePass", async (req, res) => {
//   const email = req.query.email;
//   const salt = await bcrypt.genSalt(Number(process.env.SALT));
//   const hashPassword = await bcrypt.hash(req.body.password, salt);
//   UserModel.findOneAndUpdate(
//     { email: email },
//     {
//       password: hashPassword,
//     }
//   )
//     .then((users) => res.json(users))
//     .catch((err) => res.json(err));
// });

app.put("/changePass", async (req, res) => {
  try {
    const email = req.query.email;
    const salt = await bcrypt.genSalt(Number(process.env.SALT));
    const hashPassword = await bcrypt.hash(req.body.password, salt);

    const updatedUser = await UserModel.findOneAndUpdate(
      { email: email },
      {
        password: hashPassword,
      },
      { new: true }
    );

    res.json(updatedUser);
  } catch (err) {
    res.json(err);
  }
});

app.get("/auth", (req, res) => {
  const token = req.header("Authorization").replace("Bearer ", "");
  const decodedToken = jwt.verify(token, process.env.JWTPRIVATEKEY);
  const userId = decodedToken._id;
  UserModel.findById({ _id: userId })
    .then((user) => {
      // if (!user) {
      //   return res.status(404).json({ error: "Không tìm thấy người dùng" });
      // }
      res.json(user);
    })
    .catch((err) => res.json(err));
});

app.post("/login", async (req, res) => {
  UserModel.findOne({ email: req.body.email })
    .then((user) => {
      bcrypt
        .compare(req.body.password, user.password)
        .then((isPasswordValid) => {
          if (isPasswordValid) {
            // const accessToken = jwt.sign({ userId: user.id },
            // const accessToken = generateAccessToken(response._id, role)
            // return res.status(401).json({ error: "Mật khẩu không đúng" });
            const token = user.generateAuthToken();
            res
              .status(200)
              .send({ data: token, message: "logged in successfully" });
          } else {
            res.status(500).json({ error: "Đã xảy ra lỗi" });
          }
        })
        .catch((error) => {
          res.status(500).json({ error: "Đã xảy ra lỗi" });
        });
    })
    .catch((error) => {
      res.status(500).json({ error: "Đã xảy ra lỗi" });
    });
});

app.get("/user", (req, res) => {
  UserModel.find({})
    .sort({ createdAt: -1 })
    .then((users) => res.json(users))
    .catch((err) => res.json(err));
});

// Thay doi

// app.post("/createUser", upload.single("file"), async (req, res) => {
//   const salt = await bcrypt.genSalt(Number(process.env.SALT));
//   const hashPassword = await bcrypt.hash(req.body.password, salt);

//   const userIsValid = await UserModel.findOne({ email: req.body.email });
//   if (userIsValid) {
//     res.status(409).send("User with given email already exist");
//   } else {
//     UserModel.create({
//       avatar: req.body.avatar,
//       email: req.body.email,
//       fullName: req.body.fullName,
//       userName: req.body.userName,
//       password: hashPassword,
//       status: req.body.status,
//       hot: req.body.hot,
//       role: req.body.role,
//       slug: req.body.slug,
//       description: req.body.description,
//       watchLater: req.body.watchLater,
//       likePost: req.body.likePost,
//       follow: req.body.follow,
//       follower: req.body.follower,
//     })
//       .then((users) => res.json(users))
//       .catch((err) => res.json(err));
//   }
// });

app.post("/createUser", upload.single("file"), async (req, res) => {
  try {
    const salt = await bcrypt.genSalt(Number(process.env.SALT));
    const hashPassword = await bcrypt.hash(req.body.password, salt);

    const userIsValid = await UserModel.findOne({ email: req.body.email });
    if (userIsValid) {
      return res.status(409).send("User with given email already exists");
    }

    const newUser = await UserModel.create({
      avatar: req.body.avatar,
      email: req.body.email,
      fullName: req.body.fullName,
      userName: req.body.userName,
      password: hashPassword,
      status: req.body.status,
      hot: req.body.hot,
      role: req.body.role,
      slug: req.body.slug,
      description: req.body.description,
      watchLater: req.body.watchLater,
      likePost: req.body.likePost,
      follow: req.body.follow,
      follower: req.body.follower,
    });

    res.json(newUser);
  } catch (err) {
    console.error(err);
    res.status(500).send("Server Error");
  }
});

app.get("/getUser/:id", (req, res) => {
  const id = req.params.id;
  UserModel.findById({ _id: id })
    .then((users) => res.json(users))
    .catch((err) => res.json(err));
});

app.put("/updateUser/:id", (req, res) => {
  const id = req.params.id;
  UserModel.findByIdAndUpdate(
    { _id: id },
    {
      avatar: req.body.avatars,
      email: req.body.email,
      fullName: req.body.fullName,
      userName: req.body.userName,
      password: req.body.password,
      status: req.body.status,
      hot: req.body.hot,
      role: req.body.role,
      slug: req.body.slug,
      description: req.body.description,
      watchLater: req.body.watchLater,
      likePost: req.body.likePost,
      follow: req.body.follow,
      follower: req.body.follower,
    }
  )
    .then((users) => {
      PostModel.updateMany(
        { "user.id": id },
        { "user.slug": req.body.slug, "user.userName": req.body.userName }
      ).then((post) => {
        res.json({ users, post });
      });
    })
    .catch((err) => res.json(err));
});

app.delete("/deleteUser/:id", (req, res) => {
  const id = req.params.id;
  UserModel.findByIdAndDelete({ _id: id })
    .then((users) => {
      PostModel.updateMany({ "user.id": id }, { user: [] }).then((post) => {
        res.json({ users, post });
      });
    })
    .catch((err) => res.json(err));
});

//API category

app.get("/category", (req, res) => {
  CategoryModel.find({})
    .sort({ createdAt: -1 })
    .then((category) => res.json(category))
    .catch((err) => res.json(err));
});

app.post("/createCategory", (req, res) => {
  CategoryModel.create({
    name: req.body.name,
    slug: req.body.slug,
    status: req.body.status,
  })
    .then((category) => res.json(category))
    .catch((err) => res.json(err));
});

app.get("/getCategory/:id", (req, res) => {
  const id = req.params.id;
  CategoryModel.findById({ _id: id })
    .then((category) => res.json(category))
    .catch((err) => res.json(err));
});

app.put("/updateCategory/:id", (req, res) => {
  const id = req.params.id;
  CategoryModel.findByIdAndUpdate(
    { _id: id },
    {
      name: req.body.name,
      slug: req.body.slug,
      status: req.body.status,
    }
  )
    .then((category) => {
      PostModel.updateMany(
        { "category.id": id },
        { "category.slug": req.body.slug, "category.name": req.body.name }
      ).then((post) => {
        res.json({ category, post });
      });
    })
    .catch((err) => res.json(err));
});

app.delete("/deleteCategory/:id", (req, res) => {
  const id = req.params.id;
  CategoryModel.findByIdAndDelete({ _id: id })
    .then((category) => {
      PostModel.updateMany({ "category.id": id }, { category: [] }).then(
        (post) => {
          res.json({ category, post });
        }
      );
    })
    .catch((err) => res.json(err));
});

//API post

app.get("/post", (req, res) => {
  PostModel.find({ hot: false, status: 1 })
    .sort({ createdAt: -1 })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/postFilter", (req, res) => {
  const category = req.query.category;
  const sortByLike = req.query.sortByLike;
  const sortByView = req.query.sortByView;
  let sortOption = { createdAt: -1 };
  if (sortByLike === "likeIncrease") {
    sortOption.like = 1;
    sortOption.view = 0;
    sortOption.createdAt = 0;
  }
  if (sortByLike === "likeDecrease") {
    sortOption.like = -1;
    sortOption.view = 0;
    sortOption.createdAt = 0;
  }

  if (sortByView === "viewIncrease") {
    sortOption.like = 0;
    sortOption.view = 1;
    sortOption.createdAt = 0;
  }
  if (sortByView === "viewDecrease") {
    sortOption.like = 0;
    sortOption.view = -1;
    sortOption.createdAt = 0;
  }

  let query = {};
  if (category) {
    query = { "category.slug": category };
  }

  PostModel.find(query)
    .sort(sortOption)
    .then((posts) => res.json(posts))
    .catch((error) => res.status(500).json({ message: error.message }));
});

app.get("/postHot", (req, res) => {
  PostModel.find({ hot: true, status: 1 })
    .sort({ createdAt: -1 })
    .limit(4)
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/allPost", (req, res) => {
  PostModel.find({ status: 1 })
    .sort({ createdAt: -1 })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/getPostManage", (req, res) => {
  PostModel.find({})
    .sort({ createdAt: -1 })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/postCategory/:slug", (req, res) => {
  const slug = req.params.slug;
  PostModel.find({ "category.slug": slug })
    .sort({ createdAt: -1 })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/postAuthor/:slug", (req, res) => {
  const slug = req.params.slug;
  PostModel.find({ "user.slug": slug })
    .sort({ createdAt: -1 })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/postAuthorId/:id", (req, res) => {
  const id = req.params.id;
  PostModel.find({ "user.id": id })
    .sort({ createdAt: -1 })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/postDetail/:slug", (req, res) => {
  const slug = req.params.slug;
  PostModel.findOne({ slug: slug })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.post("/createPost", (req, res) => {
  PostModel.create({
    title: req.body.title,
    slug: req.body.slug,
    status: req.body.status,
    hot: req.body.hot,
    image: req.body.image,
    content: req.body.content,
    user: req.body.user,
    category: req.body.category,
    view: req.body.view,
    like: req.body.like,
  })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.get("/getPost/:id", (req, res) => {
  const id = req.params.id;
  PostModel.findById({ _id: id })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.put("/updatePost/:id", (req, res) => {
  const id = req.params.id;
  PostModel.findByIdAndUpdate(
    { _id: id },
    {
      title: req.body.title,
      slug: req.body.slug,
      status: req.body.status,
      hot: req.body.hot,
      image: req.body.image,
      content: req.body.content,
      user: req.body.user,
      category: req.body.category,
      view: req.body.view,
      like: req.body.like,
    }
  )
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

app.put("/updatePostLike", async (req, res) => {
  const postId = req.query.id;
  const userId = req.query.userId;
  const action = req.query.action;

  try {
    const post = await PostModel.findById({ _id: postId });
    const user = await UserModel.findById({ _id: userId });

    if (!post) {
      return res.status(404).json({ message: "Post not found" });
    }
    if (!user) {
      return res.status(404).json({ message: "Post not found" });
    }
    if (user.likePost === undefined) {
      user.likePost = [];
    }

    if (action === "increment") {
      post.like += 1;
      user.likePost.push(postId);
    } else if (action === "decrement") {
      post.like -= 1;
      const index = user.likePost.indexOf(postId);
      if (index !== -1) {
        user.likePost.splice(index, 1);
      }
    } else {
      return res.status(400).json({ message: "Invalid action" });
    }
    const updatedPost = await post.save();
    const updatedUser = await user.save();
    res.json({ like: updatedPost.like, likePost: updatedUser.likePost });
  } catch (error) {
    console.error("Error updating like:", error);
    res.status(500).json({ message: "Internal server error" });
  }
});

app.delete("/deletePost/:id", (req, res) => {
  const id = req.params.id;
  PostModel.findByIdAndDelete({ _id: id })
    .then((post) => res.json(post))
    .catch((err) => res.json(err));
});

// Api comment

app.get("/comment/:id", (req, res) => {
  const idPost = req.params.id;
  CommentModel.find({ idPost: idPost, idReply: "" })
    .sort({ createdAt: -1 })
    .then((comment) => res.json(comment))
    .catch((err) => res.json(err));
});
app.get("/getReplyComment/:id", (req, res) => {
  const idPost = req.params.id;
  CommentModel.find({ idReply: idPost })
    .sort({ createdAt: -1 })
    .then((comment) => res.json(comment))
    .catch((err) => res.json(err));
});

app.post("/createComment", (req, res) => {
  CommentModel.create({
    idReply: req.body.idReply,
    idPost: req.body.idPost,
    idUser: req.body.idUser,
    idUserReply: req.body.idUserReply,
    content: req.body.content,
    like: req.body.like,
  })
    .then((comment) => res.json(comment))
    .catch((err) => res.json(err));
});

app.put("/updateComment/:id", (req, res) => {
  const id = req.params.id;
  CommentModel.findByIdAndUpdate(
    { _id: id },
    {
      content: req.body.content,
    }
  )
    .then((comment) => res.json(comment))
    .catch((err) => res.json(err));
});

app.delete("/deleteComment/:id", (req, res) => {
  const id = req.params.id;
  CommentModel.findByIdAndDelete(id)
    .then((comment) => {
      CommentModel.deleteMany({ idReply: id })
        .then((replyComment) => {
          res.json({ comment, replyComment });
        })
        .catch((err) => res.status(500).json({ error: err.message }));
    })
    .catch((err) => res.status(500).json({ error: err.message }));
});

// Api contact

app.post("/createContact", (req, res) => {
  ContactModel.create({
    content: req.body.content,
  })
    .then((contact) => res.json(contact))
    .catch((err) => res.json(err));
});

app.get("/getContact/:id", (req, res) => {
  const id = req.params.id;
  ContactModel.findById({ _id: id })
    .then((contact) => res.json(contact))
    .catch((err) => res.json(err));
});

app.put("/updateContact/:id", (req, res) => {
  const id = req.params.id;
  ContactModel.findByIdAndUpdate(
    { _id: id },
    {
      content: req.body.content,
    }
  )
    .then((contact) => res.json(contact))
    .catch((err) => res.json(err));
});

//Api report
app.post("/createReport", (req, res) => {
  ReportModel.create({
    idUser: req.body.idUser,
    idPost: req.body.idPost,
    idComment: req.body.idComment,
    reason: req.body.reason,
    content: req.body.content,
    active: req.body.active,
  })
    .then((report) => res.json(report))
    .catch((err) => res.json(err));
});

app.put("/updateReport/:id", (req, res) => {
  const id = req.params.id;
  ReportModel.findByIdAndUpdate(
    { _id: id },
    {
      active: true,
    }
  )
    .then((report) => res.json(report))
    .catch((err) => res.json(err));
});

app.get("/getReport/:id", (req, res) => {
  const id = req.params.id;
  ReportModel.findById({ _id: id })
    .then((report) => res.json(report))
    .catch((err) => res.json(err));
});
app.get("/getAllReport", (req, res) => {
  ReportModel.find({ active: false })
    .sort({ createdAt: -1 })
    .then((report) => res.json(report))
    .catch((err) => res.json(err));
});
//Api Notification

app.get("/notification", (req, res) => {
  NotificationModel.find({})
    .limit(10)
    .then((notification) => res.json(notification))
    .catch((err) => res.json(err));
});

app.post("/createNotification", (req, res) => {
  NotificationModel.create({
    userId: req.body.userId,
    postId: req.body.postId,
    content: req.body.content,
    // watch: false,
  })
    .then((notification) => res.json(notification))
    .catch((err) => res.json(err));
});

app.put("/updateNotification/:id", (req, res) => {
  const id = req.params.id;
  NotificationModel.findByIdAndUpdate(
    { _id: id },
    {
      watch: true,
    }
  )
    .then((notification) => res.json(notification))
    .catch((err) => res.json(err));
});

app.listen(3001, () => {
  console.log("app running");
});
